### ISSUE TITLE
Error when analysing PDF

### ISSUE THREAD

**Issue by andusvan** [gdelugre/origami#4] opened 2017-02-13 13:09 UTC
If I try to analyse the attached file, I get the following error:

[2017-02-13 14:07:22 +0100] PDFcop is running on target `Webshop-Quick-Guide-2014.pdf', policy = `standard'
[2017-02-13 14:07:22 +0100]   File size: 1486762 bytes
[2017-02-13 14:07:22 +0100]   MD5: 8c81e5907ed33bd64f259e6468e01d85
[error] Breaking on: "<?xpacket ..." at offset 0x7e
[error] Last exception: [Origami::InvalidObjectError] Object shall begin with '%d %d obj' statement
[error] Manually fix the file or set :ignore_errors parameter.
[error] Cannot read : "<?xpacket ..."
[error] Stopped on exception : Object shall begin with '%d %d obj' statement
[2017-02-13 14:07:22 +0100] An error occured during analysis : Origami::InvalidPDFError (Broken catalog)
[2017-02-13 14:07:22 +0100] Document rejected by policy `standard', caused by "Analysis failure".

[Webshop-Quick-Guide-2014.pdf](https://github.com/gdelugre/origami/files/771110/Webshop-Quick-Guide-2014.pdf)

**Comment by gdelugre** [comment] 2017-02-13 13:27
Thank you, I am able to reproduce it.

Probably caused by the fact the document uses ``\r`` without a ``\n``.
I'm going to look into it.

**Comment by gdelugre** [comment] 2017-02-13 14:41
Should be fixed by d320e0710ed262efa05ed79eb69d5a788a6d12ac

**Closed** 2017-02-14 10:10 UTC
